# AIRIS EPM Horizontal Pod Autoscaler
# Automatically scale based on CPU and memory usage

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: airis-epm-app-hpa
  namespace: airis-epm
  labels:
    app: airis-epm
    component: application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airis-epm-app
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
      selectPolicy: Max

---
# Custom Metrics HPA (for business metrics)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: airis-epm-app-custom-hpa
  namespace: airis-epm
  labels:
    app: airis-epm
    component: application
    type: custom-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airis-epm-app
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: External
    external:
      metric:
        name: airis_epm_requests_per_second
      target:
        type: Value
        value: "100"
  - type: External
    external:
      metric:
        name: airis_epm_response_time_p95
      target:
        type: Value
        value: "200ms"