# AIRIS EPM Secret Management
# Secure handling of sensitive configuration data

# External Secret Operator for Vault Integration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: airis-epm
spec:
  provider:
    vault:
      server: "https://vault.airis-epm.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "airis-epm"

---
# External Secret for Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: airis-epm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
  - secretKey: postgres-username
    remoteRef:
      key: database
      property: postgres_username
  - secretKey: postgres-password
    remoteRef:
      key: database
      property: postgres_password
  - secretKey: clickhouse-username
    remoteRef:
      key: database
      property: clickhouse_username
  - secretKey: clickhouse-password
    remoteRef:
      key: database
      property: clickhouse_password
  - secretKey: redis-password
    remoteRef:
      key: database
      property: redis_password
  - secretKey: mongodb-username
    remoteRef:
      key: database
      property: mongodb_username
  - secretKey: mongodb-password
    remoteRef:
      key: database
      property: mongodb_password

---
# External Secret for API Keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-credentials
  namespace: airis-epm
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-credentials
    creationPolicy: Owner
  data:
  - secretKey: jwt-secret
    remoteRef:
      key: api
      property: jwt_secret
  - secretKey: encryption-key
    remoteRef:
      key: api
      property: encryption_key
  - secretKey: webhook-secret
    remoteRef:
      key: api
      property: webhook_secret

---
# Sealed Secret for Local Development
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-credentials
  namespace: airis-epm
spec:
  encryptedData:
    dev-db-password: AgBy3i4OJSWK+PiTySYZZA9rO5QtQvNbP2lJ8VVrJdFWgJ7vp2QWvPFQFP9EGhNWJSvr1jqBOUr3cN...
    dev-api-key: AgBghU7yfgJ+BfxYTvQZqGKg/TLbjqPw4WLfM+8YvkfKjU5hRQLfCNxJBEKzwFxB8vJL/cX4lJWZt...
  template:
    metadata:
      name: dev-credentials
      namespace: airis-epm
    type: Opaque

---
# Kubernetes TLS Certificate Secret
apiVersion: v1
kind: Secret
metadata:
  name: airis-epm-tls
  namespace: airis-epm
  labels:
    app: airis-epm
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...

---
# Image Pull Secret for Private Registry
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: airis-epm
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5haXJpcy5jb21wYW55LmNvbSI6eyJ1c2VybmFtZSI6ImFpcmlzLWVwbSIsInBhc3N3b3JkIjoiYWlyaXMtZXBtLXRva2VuIiwiYXV0aCI6IllXbHlhWE10WlhCdE9tRnBjbWx6TFdWd2JTMTBiMnRsYmc9PSJ9fX0=

---
# Service Account Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: airis-epm-token
  namespace: airis-epm
  annotations:
    kubernetes.io/service-account.name: airis-epm-app
type: kubernetes.io/service-account-token